# Generated by Django 3.1.3 on 2021-10-13 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friendships', '0002_auto_20211013_2129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendship',
            options={},
        ),
    ]
