# Generated by Django 3.1.3 on 2021-10-29 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_tweetphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetphoto',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
